// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.laravelshao.learning.grpc.proto;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.laravelshao.learning.proto.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_info = 2;</code>
   * @return The responseInfo.
   */
  String getResponseInfo();
  /**
   * <code>string response_info = 2;</code>
   * @return The bytes for responseInfo.
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
